[project]
name = "mon-projet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gymnasium>=1.2.2",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "stable-baselines3>=2.7.1",
]
